//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int Rent_id { get; set; }
        public int Car_id { get; set; }
        public int User_id { get; set; }
        public string Pickup_time { get; set; }
        public string Return_time { get; set; }
        public int Total_fear { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
